<?php

/**
 * @file
 *
 */

/**
 * Implements hook_install().
 */
function ams_dev_install() {
  include_once DRUPAL_ROOT . '/profiles/minimal/minimal.install';
  minimal_install();

  // Enable the admin theme.
  db_update('system')
    ->fields(array('status' => 1))
    ->condition('type', 'theme')
    ->condition('name', 'seven')
    ->execute();
  variable_set('admin_theme', 'seven');
  variable_set('node_admin_theme', '1');

  $types = array(
    array(
      'type' => 'event',
      'name' => st('Event'),
      'base' => 'node_content',
      'description' => st("An event that you can register for."),
      'custom' => 1,
      'modified' => 1,
      'locked' => 0,
    ),
  );

  foreach ($types as $type) {
    $type = node_type_set_defaults($type);
    node_type_save($type);
    node_add_body_field($type);
  }

  $reg_type = new RedhenContactType();
  $reg_type->label = 'Staff';
  $reg_type->name = 'staff';
  $reg_type->save();

//  $field = field_create_field(
//    array(
//      'type' => 'registration',
//      'field_name' => 'field_registration',
//      'cardinality' => 1,
//      'translatable' => 0,
//      'locked' => 0,
//    )
//  );
//
//  $instance = field_create_instance(array(
//    'label' => 'Registration',
//    'field_name' => 'field_registration',
//    'entity_type' => 'node',
//    'bundle' => 'event'
//  ));
//
//  $node = new stdClass();
//  $node->type = 'event';
//  $node->title = 'Test Event 1';
//  $node->uid = 1;
//  $node->language = LANGUAGE_NONE;
//  $node->field_registration[$node->language][0] = 'registration_type_1';
//  $node->promote = 1;
//
//  node_save($node);
}
